'use client'
import "/public/css/bootstrap.min.css"
import "/public/fonts/font-icons.css"
import "/public/fonts/fonts.css"
import "/public/css/swiper-bundle.min.css"
import "/public/css/animate.css"
import "/public/css/styles.css"
import "/public/css/dashboard.css"
import { useEffect } from "react"
import { useRouter } from 'next/navigation'; // Import useRouter
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { DM_Sans, Josefin_Sans } from 'next/font/google'

const dm = DM_Sans({
	weight: ['300', '400', '500', '600', '700'],
	subsets: ['latin'],
	variable: "--dm",
	display: 'swap',
})

const josefin = Josefin_Sans({
	weight: ['300', '400', '500', '600', '700'],
	subsets: ['latin'],
	variable: "--josefin",
	display: 'swap',
})

const metadata = {
	title: 'Immofind Real Estate Matching',
	description: 'Generated by create next app',
	icons: {
		icon: ['/images/logo/favicon.svg']
	}
}

export default function RootLayout({ children }) {
	const router = useRouter(); // Get the router instance

	useEffect(() => {
		const token = localStorage.getItem("token");
		if (!token) {
			router.push("/"); // Redirect to home page if no token
		}
	}, [router]); // Make sure to include `router` in the dependency array

	return (
		<html lang="en">
			<head>
				<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
				<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.31/jspdf.plugin.autotable.min.js"></script>
			</head>
			<body className={`${dm.variable} ${josefin.variable} body`}>{children}
				<ToastContainer
					position="top-right"
					autoClose={3000}
					hideProgressBar
					newestOnTop={false}
					closeOnClick
					rtl={false}
					pauseOnFocusLoss
					draggable={false}
					pauseOnHover
					theme="light"
					closeButton={false}
					style={{ width: "auto" }}
					toastStyle={{
						padding: "16px",
						margin: "8px 0",
						borderRadius: "8px",
						boxShadow: "none",
						minHeight: "auto"
					}}
				/>
			</body>
		</html>
	)
}
